services:
  s1n1:
    image: mongo:latest
    container_name: s1n1
    ports:
      - "27017:27017"
    volumes:
      - s1n1_data:/data/db
    command: mongod --replSet rs0 --bind_ip_all

  s1n2:
    image: mongo:latest
    container_name: s1n2
    ports:
      - "27012:27017"
    volumes:
      - s1n2_data:/data/db
    command: mongod --replSet rs0 --bind_ip_all
  
  s1n3:
    image: mongo:latest
    container_name: s1n3
    ports:
      - "27013:27017"
    volumes:
      - s1n3_data:/data/db
    command: mongod --replSet rs0 --bind_ip_all

  s2n1:
    image: mongo:latest
    container_name: s2n1
    ports:
      - "27021:27017"
    volumes:
      - s2n1_data:/data/db
    command: mongod --replSet rs1 --bind_ip_all
  
  s2n2:
    image: mongo:latest
    container_name: s2n2
    ports:
      - "27022:27017"
    volumes:
      - s2n2_data:/data/db
    command: mongod --replSet rs1 --bind_ip_all
  
  s2n3:
    image: mongo:latest
    container_name: s2n3
    ports:
      - "27023:27017"
    volumes:
      - s2n3_data:/data/db
    command: mongod --replSet rs1 --bind_ip_all

  cs1:
    image: mongo:latest
    container_name: cs1
    ports:
      - "27031:27017"
    volumes:
      - cs1_data:/data/db
    command: mongod --port 27017 --replSet config_rs --configsvr --bind_ip_all
  
  cs2:
    image: mongo:latest
    container_name: cs2
    ports:
      - "27032:27017"
    volumes:
      - cs2_data:/data/db
    command: mongod --port 27017 --replSet config_rs --configsvr --bind_ip_all

  cs3:
    image: mongo:latest
    container_name: cs3
    ports:
      - "27033:27017"
    volumes:
      - cs3_data:/data/db
    command: mongod --port 27017 --replSet config_rs --configsvr --bind_ip_all
  
  mongo_router:
    image: mongo:latest
    container_name: mongo_router
    ports:
      - "27041:27017"
    depends_on:
      - cs1
      - cs2
      - cs3
      - s1n1
      - s2n1
    command: mongos --port 27017 --configdb config_rs/cs1:27017,cs2:27017,cs3:27017 --bind_ip_all

volumes:
  s1n1_data:
  s1n2_data:
  s1n3_data:
  s2n1_data:
  s2n2_data:
  s2n3_data:
  cs1_data:
  cs2_data:
  cs3_data: