services:
  s1n1:
    image: mongo:latest
    container_name: s1n1
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pvs123
    ports:
      - "27017:27017"
    volumes:
      - ./../mongo-keyfile:/data/mongo-keyfile
      - s1n1_data:/data/db
    command: mongod --auth --keyFile /data/mongo-keyfile --replSet rs0 --bind_ip_all

volumes:
  s1n1_data: