version: '3'
services:
  cn1:
    image: cassandra:latest
    container_name: cn1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=my_cluster
      - CASSANDRA_SEEDS=cn1
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=r1
    volumes:
      - cassandra_data1:/var/lib/cassandra
    networks:
      - cassandra_network

  cn2:
    image: cassandra:latest
    container_name: cn2
    environment:
      - CASSANDRA_CLUSTER_NAME=my_cluster
      - CASSANDRA_SEEDS=cn1
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=r1
    volumes:
      - cassandra_data2:/var/lib/cassandra
    networks:
      - cassandra_network

  # cn3:
  #   image: cassandra:latest
  #   container_name: cn3
  #   environment:
  #     - CASSANDRA_CLUSTER_NAME=my_cluster
  #     - CASSANDRA_SEEDS=cn1
  #     - CASSANDRA_DC=dc1
  #     - CASSANDRA_RACK=r1
  #   volumes:
  #     - cassandra_data3:/var/lib/cassandra
  #   networks:
  #     - cassandra_network

  # cn4:
  #   image: cassandra:latest
  #   container_name: cn4
  #   environment:
  #     - CASSANDRA_CLUSTER_NAME=my_cluster
  #     - CASSANDRA_SEEDS=cn1
  #     - CASSANDRA_DC=dc1
  #     - CASSANDRA_RACK=r1
  #   volumes:
  #     - cassandra_data4:/var/lib/cassandra
  #   networks:
  #     - cassandra_network

  # cn5:
  #   image: cassandra:latest
  #   container_name: cn5
  #   environment:
  #     - CASSANDRA_CLUSTER_NAME=my_cluster
  #     - CASSANDRA_SEEDS=cn1
  #     - CASSANDRA_DC=dc1
  #     - CASSANDRA_RACK=r1
  #   volumes:
  #     - cassandra_data5:/var/lib/cassandra
  #   networks:
  #     - cassandra_network  

networks:
  cassandra_network:
    driver: bridge

volumes:
  cassandra_data1:
  cassandra_data2:
  cassandra_data3:
  cassandra_data4:
  cassandra_data5:
